### ISSUE TITLE
TST: numpy versions > 1.15.4 don't work in CI

### ISSUE THREAD

**Issue by aburrell** [aburrell/ocbpy#50]
Appveyor and Travis CI testing don't work with numpy versions above 1.15.4.  This issue has been brought up to numpy: https://github.com/numpy/numpy/issues/14012

**Comment by jklenzing** [comment]
It looks like this issue has been addressed in numpy 1.19.0rc1.

https://github.com/numpy/numpy/pull/16239

I ran a test branch with the pre-release version, and things are looking good.  Once there official release comes out, we have a potential solution (and more problems!)

https://travis-ci.org/github/jklenzing/ocbpy/jobs/692382995

**Comment by aburrell** [comment]
That looks like a problem I can solve, though!  I'm glad the issue is being addressed.
