### ISSUE TITLE
Possible sign error in the logical operator in calc_ocb_vec_sign()

### ISSUE THREAD

**Issue by jpreistad** [aburrell/ocbpy#59]
Running the scale_vector() function with the following parameters:

Vector data location:
mlt = 0.67159322
mlat = 51.5

Oval parameters:
oval_r = 18.20044441
center_r = 5.38516481
center_mlt = 1.4534273

Vector components:
east = -71.57035515
north = 28.

Scaling function:
Same as eq 3 in Chisham 2017, with Rb = 75.34

I get the vsign[1] variable at line 564 (the sign of the northward component of the vector represented in OCB coordinates) to be 0. This means that the sign has not been set in the calc_ocb_vec_sign() function. I think the reason is a bug in a logic operator, specififally at line 700:
I think the present code:
quads[1][2] and self.aacgm_naz > minus_pole

should be replaced with 
quads[1][2] and self.aacgm_naz < minus_pole

I hope this information will make it possible to fix the bug.

**Comment by aburrell** [comment]
You did indeed find the bug.  I checked against my research notebook and it was supposed to be `quads[1][2] and self.aacgm_naz <= minus_pole`.

**Comment by aburrell** [comment]
@jpreistad when you get a chance, could you check out the fix in PR #65 ?
