### ISSUE TITLE
Negative number inside sqrt encountered

### ISSUE THREAD

**Issue by jpreistad** [aburrell/ocbpy#60]
Due to machine precision, the variable "hav_pole_angle" can get a small but negative value. This result in NaN output on line 800 in ocb_scaling.py I think a reasonable fix could be to take abs(hav_pole_angle) before passing to archav() function.

**Comment by aburrell** [comment]
@jpreistad could you test the fix implemented in PR #63 to see if it addresses your problem?  I decided to test the angle within the `archav` routine itself and assume single precision is good enough.

**Comment by jpreistad** [comment]
The fix looks good. Please note, I have not had the time to actually run the OCBpy code after you made the fix in #63 , but I implemented your fix in my own version that handle array-input. There it runs just fine.

**Comment by aburrell** [comment]
That's more external testing than this code has historically gotten so I will take it.  Thanks!
